# Generated by Django 5.2.6 on 2025-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_application_options_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
