# Generated by Django 4.2.7 on 2025-09-20 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_user_sms_notifications_enabled'),
    ]

    operations = [
        # Update RegistryBranch model
        migrations.RenameField(
            model_name='registrybranch',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='registrybranch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrybranch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registrybranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrybranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='registrybranch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        
        # Update DocumentType model
        migrations.AddField(
            model_name='documenttype',
            name='processing_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        
        # Create SystemConfiguration model
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Civil Registry System', max_length=200)),
                ('site_description', models.TextField(default='Digital Civil Registry Management System')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registration', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('max_file_size', models.PositiveIntegerField(default=10)),
                ('allowed_file_types', models.CharField(default='pdf,jpg,jpeg,png,doc,docx', max_length=200)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('auto_approve_applications', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sms_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, blank=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
