# Generated by Django 4.2.7 on 2025-09-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20250920_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
        migrations.RemoveField(
            model_name='registrybranch',
            name='contact_info',
        ),
    ]
